// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlShort.Repositories;

namespace UrlShort.Repositories.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UrlShort.Domain.Models.UrlEntity", b =>
                {
                    b.Property<string>("ShortedUrl")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShortedUrl");

                    b.ToTable("UrlEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
